-- Create viewers table for tracking live viewers
CREATE TABLE IF NOT EXISTS viewers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id TEXT NOT NULL,
  viewer_id TEXT NOT NULL,
  last_seen TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create unique constraint on video_id and viewer_id combination
CREATE UNIQUE INDEX IF NOT EXISTS viewers_video_viewer_idx ON viewers(video_id, viewer_id);

-- Create index on video_id and last_seen for efficient counting
CREATE INDEX IF NOT EXISTS viewers_video_last_seen_idx ON viewers(video_id, last_seen);

-- Optional: Create a policy to allow anonymous inserts and reads
-- alter table viewers enable row level security;
-- create policy "Allow anonymous read" on viewers for select using (true);
-- create policy "Allow anonymous insert" on viewers for insert with check (true);
